// import { Inter } from 'next/font/google';
import Head from 'next/head';

import styles from '@/styles/Home.module.css';

import PieChart from '../components/PieChart';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PieChart
          data={[
            { name: 'svelte', value: '10.25' },
            { name: 'vue', value: '25' },
            { name: 'react', value: '64.75' },
          ]}
          width={300}
          height={300}
          color={['#F5FEFA', '#ADFDFB', '#83F3FA', '#63E2F5', '#32C9EF']}
        />
      </main>
    </>
  );
}
