// import { Inter } from 'next/font/google';
import Head from 'next/head';

import BarChart from '@/components/BarChart';
import styles from '@/styles/Home.module.css';

import PieChart from '../components/PieChart';

const RAW_FAKE_BAR_DATA = Array.from({ length: 26 }, (_, i) => {
  return {
    name: String.fromCharCode(i + 65),
    value: Math.random() * 100,
  };
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PieChart
          data={[
            { name: 'svelte', value: '1.25' },
            { name: 'vue', value: '25' },
            { name: 'react', value: '64.75' },
          ]}
          width={300}
          height={300}
          color={['#F5FEFA', '#ADFDFB', '#83F3FA', '#63E2F5', '#32C9EF']}
        />

        <BarChart
          width={800}
          height={600}
          data={RAW_FAKE_BAR_DATA}
          margin={{ top: 10, right: 50, bottom: 30, left: 50 }}
          color="#752bed"
        />

        <div
          style={{
            width: '100px',
            height: '50px',
            background: 'white',
            paddingBottom: '10px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'black',
          }}
        >
          <span>글자</span>
        </div>
      </main>
    </>
  );
}
